apiVersion: v1
kind: Service
metadata:
  name: docs-${VERSIONS_TAG}
  namespace: pxdocs
spec:
  type: NodePort
  ports:
  - port: 80
    name: docs-port
    protocol: TCP
  selector:
    app: docs-${VERSIONS_TAG}
