apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ingress-pxbackup-2.5
  namespace: pxdocs-backup
spec:
  secretName: ingress-pxbackup-2.5-tls
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  dnsNames:
  - 2.5.backup.docs.portworx.com