apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ingress-pxbackup-2.4
  namespace: pxdocs-backup
spec:
  secretName: ingress-pxbackup-2.4-tls
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  dnsNames:
  - 2.4.backup.docs.portworx.com