apiVersion: v1
kind: Service
metadata:
  name: saasbackup-${VERSIONS_TAG}
  namespace: pxdocs-saasbackup
spec:
  type: ClusterIP
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: saasbackup-${VERSIONS_TAG}

